const authors = [
  {
    id: '1',
    name: 'Albertine Jeffries',
    dob: '1979-08-22',
    pob: 'Canada',
    books: 'Fully-configurable foreground project',
  },
  {
    id: '2',
    name: 'Gran Cheake',
    dob: '1989-11-14',
    pob: 'Burma',
    books: 'Adaptive bifurcated encoding',
  },
  {
    id: '3',
    name: 'Arleen MacAindreis',
    dob: '1987-09-12',
    pob: 'France',
    books: 'Mandatory stable pricing structure',
  },
  {
    id: '4',
    name: 'Mercie Savery',
    dob: '1992-04-05',
    pob: 'Thailand',
    books: 'Balanced 24/7 ability',
  },
  {
    id: '5',
    name: 'Minna Nockells',
    dob: '1996-02-01',
    pob: 'Japan',
    books: 'Sharable needs-based instruction set',
  },
  {
    id: '6',
    name: 'Catha Ocurrane',
    dob: '1997-03-12',
    pob: 'Oahu',
    books: 'Distributed upward-trending alliance',
  },
  {
    id: '7',
    name: 'Devonna Philp',
    dob: '1991-05-16',
    pob: 'Russia',
    books: 'Intuitive reciprocal orchestration',
  },
  {
    id: '8',
    name: 'Reinwald Fleeman',
    dob: '1987-08-22',
    pob: 'Spain',
    books: 'Configurable intermediate circuit',
  },
  {
    id: '9',
    name: 'Catharine Ormeilly',
    dob: '2144-09-18',
    pob: 'Scotland',
    books: 'Assimilated multi-tasking matrices',
  },
  {
    id: '10',
    name: 'Coralyn Thorowgood',
    dob: '2198-06-19',
    pob: 'Kosovo',
    books: 'Expanded grid-enabled methodology',
  },
  {
    id: '11',
    name: 'Garrek Jutson',
    dob: '1986-03-12',
    pob: 'Mongolia',
    books: 'Persevering discrete parallelism',
  },
  {
    id: '12',
    name: 'Rebe Johnston',
    dob: '1998-02-12',
    pob: 'Vietnam',
    books: 'Robust intermediate process improvement',
  },
  {
    id: '13',
    name: 'Elsie MacDuff',
    dob: '1984-12-05',
    pob: 'Norway',
    books: 'Reverse-engineered 5th generation open architecture',
  },
  {
    id: '14',
    name: 'Cooper Wharf',
    dob: '1997-08-22',
    pob: 'Nepal',
    books: 'Cross-platform hybrid hardware',
  },
  {
    id: '15',
    name: 'Henrie Batrip',
    dob: '2004-07-19',
    pob: 'Macedonia',
    books: 'Enhanced discrete data-warehouse',
  },
  {
    id: '16',
    name: 'Berton Dymock',
    dob: '2027-03-12',
    pob: 'Pakistan',
    books: 'Stand-alone systemic success',
  },
  {
    id: '17',
    name: 'Lanie Hurler',
    dob: '1977-04-09',
    pob: 'Colombia',
    books: 'Realigned multi-state complexity',
  },
  {
    id: '18',
    name: 'Ianthe Crackel',
    dob: '1987-06-23',
    pob: 'Ohio',
    books: 'Customizable dynamic internet solution',
  },
  {
    id: '19',
    name: 'Thane Taye',
    dob: '2188-04-19',
    pob: 'Mars',
    books: 'Multi-channelled neutral secured line',
  },
  {
    id: '20',
    name: 'Anthe Ormston',
    dob: '2084-12-01',
    pob: 'New Tokyo',
    books: 'Optional even-keeled open system',
  },
];

module.exports = { authors };
